project:
  type: website
  output-dir: docs

css:
  - https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap

mainfont: PT Sans
fontsize: 14pt
highlight-style: "monokai"

website:
  title: "My Notes"
  sidebar:
    collapse-level: 1
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Deep Learning"
        contents: 
          - href: pages/DL/IntroDL.md
            text: Backpropogation
      - section: "Multi Armed Bandits"
        contents: 
          - href: pages/MAB/IntroMAB.md
            text: Introduction to Multi-Armed Bandits
      - section: "Large Language Models"
        contents: 
          - href: pages/LLM/Week5.md
            text: LLMs
         
format:
  html:
    theme: 
      light: [zephyr, styles_light.scss]
      dark: [darkly, styles.scss]
    toc: true
